config/routes.rb
Rails.application.routes.draw do
  get 'collections/index'
  devise_for :users
  root 'games#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :games
  resources :user_games, only: [:create, :destroy]
  get 'collection', to: 'collections#index'
  get '/games/:id/q_and_as', to: 'games#q_and_as', as: 'game_q_and_as'

  resources :games do
    resources :comments, only: [:create, :destroy]
    resources :ratings, only: [:create]
    resources :house_rules
  end
  resources :chatrooms, param: :slug, only: [:index, :new, :create, :show, :destroy]
  resources :chatrooms do
    resources :messages
  end
  
  get '/recommendations', to: 'users#recommendations'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  before_save :generate_slug
  belongs_to :owner, class_name: "User"
  has_many :messages
  def to_param
    slug
  end

  private

  def generate_slug
    self.slug = name.parameterize
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  self.inheritance_column = 'category'
  has_many :user_games
  has_many :users, through: :user_games
  has_many :comments
  has_many :ratings
  has_many :house_rules
  has_many :game_variants
  has_many :q_and_as
  def calculate_average_rate
    if ratings.any?
      (((rate.to_f * (ratings.count + 1)) + ratings.sum(:value)) / (ratings.count + 2)).round(1)
    else
      rate.to_f.round(1)
    end
  end
end

app/models/game_variant.rb
class GameVariant < ApplicationRecord
  belongs_to :game
end

app/models/house_rule.rb
class HouseRule < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :name, presence: true
  validates :content, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/q_and_a.rb
class QAndA < ApplicationRecord
  belongs_to :game
end

app/models/rating.rb
class Rating < ApplicationRecord
  GAME_RATING_RANGE = (0..5)

  belongs_to :game
  belongs_to :user

  validates :value, presence: true, inclusion: { in: GAME_RATING_RANGE }
  validates :user_id, uniqueness: { scope: :game_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :house_rules
  has_many :comments
  has_many :user_games
  has_many :games, through: :user_games
  validates :username, presence: true, uniqueness: true       
  has_many :messages
  has_many :chatrooms, foreign_key: :owner_id

  def recommendations
    recommended_games = []

    # Find games of the same type that are not in the user's collection
    same_type_games = Game.where(type: games.pluck(:type)).where.not(id: games.pluck(:id))

    # If there are games of the same type, add them to the recommended list
    unless same_type_games.empty?
      recommended_games.concat(same_type_games.to_a)
    end

    # If there are less than 3 same type games, add randomly selected games to the recommended list
    if recommended_games.length < 3
      random_games = Game.where.not(id: games.pluck(:id)).limit(3 - recommended_games.length).to_a
      recommended_games.concat(random_games)
    end

    recommended_games
  end
end

app/models/user_game.rb
class UserGame < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  def index
    @games = Game.paginate(page: params[:page], per_page: 6)
  end
  
  def show
    @game = Game.find(params[:id])
  end

  def q_and_as
    @game = Game.find(params[:id])
    @q_and_as = @game.q_and_as
  end
end

app/controllers/house_rules_controller.rb
class HouseRulesController < ApplicationController
  before_action :set_game
  before_action :set_house_rule, only: [:show, :edit, :update, :destroy]
  before_action :authorize_house_rule, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @house_rules = @game.house_rules
  end

  def show
  end

  def new
    @house_rule = HouseRule.new
  end

  def create
    @house_rule = @game.house_rules.build(house_rule_params)
    @house_rule.user = current_user

    if @house_rule.save
      redirect_to game_house_rules_path(@game), notice: 'House rule was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @house_rule.update(house_rule_params)
      redirect_to game_house_rules_path(@game), notice: 'House rule was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @house_rule.destroy
    redirect_to game_house_rules_path(@game), notice: 'House rule was successfully destroyed.'
  end

  private

  def set_game
    @game = Game.find(params[:game_id])
  end

  def set_house_rule
    @house_rule = @game.house_rules.find(params[:id])
  end

  def authorize_house_rule
    unless @house_rule.user == current_user
      redirect_to game_house_rule_path(@game, @house_rule), alert: 'You are not authorized to perform this action.'
    end
  end

  def house_rule_params
    params.require(:house_rule).permit(:name, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/house_rules_helper.rb
module HouseRulesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/user_games_helper.rb
module UserGamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/house_rules/edit.html.erb
<!-- Display all the house rules for the game -->
<h1>House Rules for <%= @game.name %></h1>
<ul class="list-group">
  <% @game.house_rules.sort_by { |hr| hr.user_id == current_user.id ? 0 : 1 }.each do |house_rule| %>
    <li class="list-group-item">
      <div class="d-flex justify-content-between">
        <div>
          <strong><%= house_rule.name %></strong>: <%= house_rule.content %>
        </div>
        <% if house_rule.user_id == current_user.id %>
        <div>
          <%= button_to "Edit", edit_game_house_rule_path(@game, house_rule), method: :get, class: "btn btn-primary mr-2" %>
          <%= button_to "Delete", game_house_rule_path(@game, house_rule), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
        </div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>


<!-- Form to edit an existing house rule -->
<h2>Edit House Rule</h2>
<%= form_with(model: [@game, @house_rule], local: true, class: "form", method: "patch") do |form| %>

  <div class="form-group">
    <%= form.label :name, class: "control-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content, class: "control-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Update", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/house_rules/index.html.erb
<!-- Display all the house rules for the game -->
<h1>House Rules for <%= @game.name %></h1>
<ul class="list-group">
  <% @game.house_rules.sort_by { |hr| hr.user_id == current_user.id ? 0 : 1 }.each do |house_rule| %>
    <li class="list-group-item">
      <div class="d-flex justify-content-between">
        <div>
          <strong><%= house_rule.name %></strong>: <%= house_rule.content %>
        </div>
        <% if house_rule.user_id == current_user.id %>
        <div>
          <%= button_to "Edit", edit_game_house_rule_path(@game, house_rule), method: :get, class: "btn btn-primary mr-2" %>
          <%= button_to "Delete", game_house_rule_path(@game, house_rule), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
        </div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>


<!-- Form to add a new house rule -->
<h2>Your House Rule</h2>
<%= form_with(url: game_house_rules_path(@game), local: true, class: "form") do |form| %>

  <div class="form-group">
    <%= form.label :name, class: "control-label" %>
    <%= form.text_field :name, class: "form-control",  name: "house_rule[name]" %>
  </div>

  <div class="form-group">
    <%= form.label :content, class: "control-label" %>
    <%= form.text_area :content, class: "form-control", name: "house_rule[content]" %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>