config/routes.rb
Rails.application.routes.draw do
  get 'collections/index'
  devise_for :users
  root 'games#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :games
  resources :user_games, only: [:create, :destroy]
  get 'collection', to: 'collections#index'
  get '/games/:id/q_and_as', to: 'games#q_and_as', as: 'game_q_and_as'

  resources :games do
    resources :comments, only: [:create, :destroy]
    resources :ratings, only: [:create]
    resources :house_rules
  end
  resources :chatrooms, param: :slug, only: [:index, :new, :create, :show, :destroy]
  resources :chatrooms do
    resources :messages
  end
  
  get '/recommendations', to: 'users#recommendations'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  before_save :generate_slug
  belongs_to :owner, class_name: "User"
  has_many :messages
  def to_param
    slug
  end

  private

  def generate_slug
    self.slug = name.parameterize
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  self.inheritance_column = 'category'
  has_many :user_games
  has_many :users, through: :user_games
  has_many :comments
  has_many :ratings
  has_many :house_rules
  has_many :game_variants
  has_many :q_and_as
  def calculate_average_rate
    if ratings.any?
      (((rate.to_f * (ratings.count + 1)) + ratings.sum(:value)) / (ratings.count + 2)).round(1)
    else
      rate.to_f.round(1)
    end
  end
end

app/models/game_variant.rb
class GameVariant < ApplicationRecord
  belongs_to :game
end

app/models/house_rule.rb
class HouseRule < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :name, presence: true
  validates :content, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/q_and_a.rb
class QAndA < ApplicationRecord
  belongs_to :game
end

app/models/rating.rb
class Rating < ApplicationRecord
  GAME_RATING_RANGE = (0..5)

  belongs_to :game
  belongs_to :user

  validates :value, presence: true, inclusion: { in: GAME_RATING_RANGE }
  validates :user_id, uniqueness: { scope: :game_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :house_rules
  has_many :comments
  has_many :user_games
  has_many :games, through: :user_games
  validates :username, presence: true, uniqueness: true       
  has_many :messages
  has_many :chatrooms, foreign_key: :owner_id

  def recommendations
    recommended_games = []

    # Find games of the same type that are not in the user's collection
    same_type_games = Game.where(type: games.pluck(:type)).where.not(id: games.pluck(:id))

    # If there are games of the same type, add them to the recommended list
    unless same_type_games.empty?
      recommended_games.concat(same_type_games.to_a)
    end

    # If there are less than 3 same type games, add randomly selected games to the recommended list
    if recommended_games.length < 3
      random_games = Game.where.not(id: games.pluck(:id)).limit(3 - recommended_games.length).to_a
      recommended_games.concat(random_games)
    end

    recommended_games
  end
end

app/models/user_game.rb
class UserGame < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chatrooms = Chatroom.all
  end

  def new
    @chatroom = Chatroom.new
  end

  def create
    @chatroom = current_user.chatrooms.build(chatroom_params)

    if @chatroom.save
      redirect_to chatroom_path(@chatroom)
    else
      render :new
    end
  end

  def show
    @chatroom = Chatroom.find_by(slug: params[:slug])
    puts "Slug: #{params[:id]}"
    raise "Chatroom not found" if @chatroom.nil?
    @message = Message.new
    @messages = @chatroom.messages.where(chatroom_id: @chatroom.id).includes(:user)
  end
  

  def destroy
    @chatroom = Chatroom.find_by(slug: params[:id])
    @chatroom.destroy

    redirect_to chatrooms_path
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:name)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  def index
    @games = Game.paginate(page: params[:page], per_page: 6)
  end
  
  def show
    @game = Game.find(params[:id])
  end

  def q_and_as
    @game = Game.find(params[:id])
    @q_and_as = @game.q_and_as
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/house_rules_helper.rb
module HouseRulesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/user_games_helper.rb
module UserGamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatrooms/index.html.erb
<div class="container">
  <h1 class="mb-4">Chatrooms</h1>

  <div class="card">
    <ul class="list-group list-group-flush">
      <% @chatrooms.each do |chatroom| %>
        <li class="list-group-item"><%= link_to chatroom.name, chatroom_path(chatroom) %></li>
      <% end %>
    </ul>
  </div>

  <%= link_to "Create a new chatroom", new_chatroom_path, class: "btn btn-primary mt-3" %>
</div>

app/views/chatrooms/new.html.erb
<!-- app/views/chatrooms/new.html.erb -->
<div class="container">
  <h1>Create a new chatroom</h1>

  <%= form_with(model: @chatroom, local: true) do |form| %>
    <% if @chatroom.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(@chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

        <ul>
          <% @chatroom.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control", placeholder: "Enter the chatroom name" %>
    </div>

    <%= form.submit "Create Chatroom", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/chatrooms/show.html.erb
<div class="container">
  <h1><%= @chatroom.name %></h1>

  <div class="row">
    <div class="col-md-8">
      <ul id="messages" class="list-unstyled">
        <% @chatroom.messages.each do |message| %>
          <li class="mb-3">
            <strong><%= message.user.username %>:</strong>
            <%= message.body %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-4">
      <%= form_with(model: [@chatroom, @message], remote: true, class: "mb-3") do |form| %>
        <div class="form-group">
          <%= form.text_area :body, placeholder: "Type your message...", class: "form-control" %>
        </div>
        <%= form.submit "Send", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>