config/routes.rb
Rails.application.routes.draw do
  get 'collections/index'
  devise_for :users
  root 'games#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :games
  resources :user_games, only: [:create, :destroy]
  get 'collection', to: 'collections#index'
  get '/games/:id/q_and_as', to: 'games#q_and_as', as: 'game_q_and_as'

  resources :games do
    resources :comments, only: [:create, :destroy]
    resources :ratings, only: [:create]
    resources :house_rules
  end
  resources :chatrooms, param: :slug, only: [:index, :new, :create, :show, :destroy]
  resources :chatrooms do
    resources :messages
  end
  
  get '/recommendations', to: 'users#recommendations'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  before_save :generate_slug
  belongs_to :owner, class_name: "User"
  has_many :messages
  def to_param
    slug
  end

  private

  def generate_slug
    self.slug = name.parameterize
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  self.inheritance_column = 'category'
  has_many :user_games
  has_many :users, through: :user_games
  has_many :comments
  has_many :ratings
  has_many :house_rules
  has_many :game_variants
  has_many :q_and_as
  def calculate_average_rate
    if ratings.any?
      (((rate.to_f * (ratings.count + 1)) + ratings.sum(:value)) / (ratings.count + 2)).round(1)
    else
      rate.to_f.round(1)
    end
  end
end

app/models/game_variant.rb
class GameVariant < ApplicationRecord
  belongs_to :game
end

app/models/house_rule.rb
class HouseRule < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :name, presence: true
  validates :content, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/q_and_a.rb
class QAndA < ApplicationRecord
  belongs_to :game
end

app/models/rating.rb
class Rating < ApplicationRecord
  GAME_RATING_RANGE = (0..5)

  belongs_to :game
  belongs_to :user

  validates :value, presence: true, inclusion: { in: GAME_RATING_RANGE }
  validates :user_id, uniqueness: { scope: :game_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :house_rules
  has_many :comments
  has_many :user_games
  has_many :games, through: :user_games
  validates :username, presence: true, uniqueness: true       
  has_many :messages
  has_many :chatrooms, foreign_key: :owner_id

  def recommendations
    recommended_games = []

    # Find games of the same type that are not in the user's collection
    same_type_games = Game.where(type: games.pluck(:type)).where.not(id: games.pluck(:id))

    # If there are games of the same type, add them to the recommended list
    unless same_type_games.empty?
      recommended_games.concat(same_type_games.to_a)
    end

    # If there are less than 3 same type games, add randomly selected games to the recommended list
    if recommended_games.length < 3
      random_games = Game.where.not(id: games.pluck(:id)).limit(3 - recommended_games.length).to_a
      recommended_games.concat(random_games)
    end

    recommended_games
  end
end

app/models/user_game.rb
class UserGame < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  def index
    @games = Game.paginate(page: params[:page], per_page: 6)
  end
  
  def show
    @game = Game.find(params[:id])
  end

  def q_and_as
    @game = Game.find(params[:id])
    @q_and_as = @game.q_and_as
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def recommendations
    @recommended_games = current_user.recommendations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/house_rules_helper.rb
module HouseRulesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/user_games_helper.rb
module UserGamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<div class="container mt-4">
  <h1 class="text-center mb-4">All Games</h1>
  <% @games.each do |game| %>
    <div class="row mb-4 justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to game.name, game_path(game) %></h5>
            <p class="card-text"><strong>Number of Players:</strong> <%= game.number_of_players %> | <strong>Rate:</strong> <%= game.rate %>| <strong>Type:</strong> <%= game.type %></p>

          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="d-flex justify-content-center">
  <%= will_paginate @games %>
</div>

app/views/games/q_and_as.html.erb
<div class="container">
  <h1><%= @game.name %> Q&A</h1>
  
  <% if @q_and_as.any? %>
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th>Question</th>
          <th>Answer</th>
        </tr>
      </thead>
      <tbody>
        <% @q_and_as.each do |q_and_a| %>
          <tr>
            <td><%= q_and_a.question %></td>
            <td><%= q_and_a.answer %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>There are currently no Q&As for this game.</p>
  <% end %>
</div>

app/views/games/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-md-8">
      <h1><%= @game.name %></h1>

      <p><strong>Number of Players:</strong> <%= @game.number_of_players %></p>
      <p><strong>Age limit:</strong> <%= @game.age_limit %></p>
      <p><strong>Description:</strong> <%= @game.description %></p>
      <p><strong>Rules:</strong> <%= @game.rules %></p>

     
      <%= form_with(url: current_user.games.include?(@game) ? url_for(user_game_path) : url_for(user_games_path), method: current_user.games.include?(@game) ? :delete : :post, local: true) do |form| %>

        <%= form.hidden_field :game_id, value: @game.id %>
        <% if current_user.games.include?(@game) %>
          <%= form.submit "Remove from collection", class: "btn btn-danger" %>
        <% else %>
          <%= form.submit "Add to collection", class: "btn btn-primary" %>
        <% end %>
      <% end %>
      
      <% if @game.game_variants.any? %>
        <h2>Here To Buy </h2>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Link</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody>
            <% @game.game_variants.each do |variant| %>
              <tr>
                <td><%= variant.name %></td>
                <td><%= link_to truncate(variant.link, length: 30), variant.link, target: "_blank" %></td>
                <td><%= variant.price %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>

      <h2>Comments</h2>
      <% @game.comments.sort_by { |comment| comment.user == current_user ? 0 : 1 }.each do |comment| %>
        <div class="comment-container">
          <p class="comment"><strong><%= comment.user.username %>:</strong> <%= comment.content %></p>
          <% if comment.user == current_user %>
            <%= button_to game_comment_path(@game, comment), method: :delete, class: "delete-comment-btn", data: { confirm: "Are you sure you want to delete this comment?" } do %>
              <i class="fas fa-times"></i>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <% if user_signed_in? %>
        <%= form_with(url: game_comments_path(@game), method: :post, local: true) do |form| %>
          <%= form.hidden_field :game_id, value: @game.id %>
          <div class="form-group">
            <%= form.label :content, "Add a comment" %>
            <%= form.text_area :content, class: "form-control" , name: "comment[content]"%>
          </div>
          <%= form.submit "Add comment", class: "btn btn-primary" %>
        <% end %>
      <% end %>

    </div>
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Rate</h5>
          <p class="card-text"><%= @game.calculate_average_rate %></p>
            <% if user_signed_in? && !@game.ratings.exists?(user_id: current_user.id) %>
              <%= form_with(url: game_ratings_path(@game), method: :post, local: true) do |form| %>
                <%= form.hidden_field :game_id, value: @game.id %>
                <div class="form-group">
                  <%= form.label :value, "Choose a rating" %>
                  <%= form.select :value, Rating::GAME_RATING_RANGE, {}, {class: "form-control", name: "rating[value]"} %>
                </div>
                <%= form.submit "Submit rating", class: "btn btn-primary" %>
              <% end %>
            <% end %>
            <%= link_to "House Rules", game_house_rules_path(@game), class: "btn btn-primary" %>
            <%= link_to "Q&A", game_q_and_as_path(@game), class: "btn btn-primary" %>

        </div>
      </div>
    </div>

  </div>
</div>

app/views/users/recommendations.html.erb
<h1>Recommended Games</h1>

<ul class="list-group">
  <% @recommended_games.each do |game| %>
    <li class="list-group-item">
      <%= link_to game.name, game_path(game.id) %>
      <span class="badge badge-secondary float-right"><%= game.type %></span>
    </li>
  <% end %>
</ul>