config/routes.rb
Rails.application.routes.draw do
  get 'collections/index'
  devise_for :users
  root 'games#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :games
  resources :user_games, only: [:create, :destroy]
  get 'collection', to: 'collections#index'
  get '/games/:id/q_and_as', to: 'games#q_and_as', as: 'game_q_and_as'

  resources :games do
    resources :comments, only: [:create, :destroy]
    resources :ratings, only: [:create]
    resources :house_rules
  end
  resources :chatrooms, param: :slug, only: [:index, :new, :create, :show, :destroy]
  resources :chatrooms do
    resources :messages
  end
  
  get '/recommendations', to: 'users#recommendations'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  before_save :generate_slug
  belongs_to :owner, class_name: "User"
  has_many :messages
  def to_param
    slug
  end

  private

  def generate_slug
    self.slug = name.parameterize
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  self.inheritance_column = 'category'
  has_many :user_games
  has_many :users, through: :user_games
  has_many :comments
  has_many :ratings
  has_many :house_rules
  has_many :game_variants
  has_many :q_and_as
  def calculate_average_rate
    if ratings.any?
      (((rate.to_f * (ratings.count + 1)) + ratings.sum(:value)) / (ratings.count + 2)).round(1)
    else
      rate.to_f.round(1)
    end
  end
end

app/models/game_variant.rb
class GameVariant < ApplicationRecord
  belongs_to :game
end

app/models/house_rule.rb
class HouseRule < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :name, presence: true
  validates :content, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/q_and_a.rb
class QAndA < ApplicationRecord
  belongs_to :game
end

app/models/rating.rb
class Rating < ApplicationRecord
  GAME_RATING_RANGE = (0..5)

  belongs_to :game
  belongs_to :user

  validates :value, presence: true, inclusion: { in: GAME_RATING_RANGE }
  validates :user_id, uniqueness: { scope: :game_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :house_rules
  has_many :comments
  has_many :user_games
  has_many :games, through: :user_games
  validates :username, presence: true, uniqueness: true       
  has_many :messages
  has_many :chatrooms, foreign_key: :owner_id

  def recommendations
    recommended_games = []

    # Find games of the same type that are not in the user's collection
    same_type_games = Game.where(type: games.pluck(:type)).where.not(id: games.pluck(:id))

    # If there are games of the same type, add them to the recommended list
    unless same_type_games.empty?
      recommended_games.concat(same_type_games.to_a)
    end

    # If there are less than 3 same type games, add randomly selected games to the recommended list
    if recommended_games.length < 3
      random_games = Game.where.not(id: games.pluck(:id)).limit(3 - recommended_games.length).to_a
      recommended_games.concat(random_games)
    end

    recommended_games
  end
end

app/models/user_game.rb
class UserGame < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/user_games_helper.rb
module UserGamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardgameCo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>   
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to "BoardgameCollect", root_path, class: "navbar-brand", style: "font-size: 30px;" %>
      </div> 
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Games', games_path, class: "nav-link" %>
                <%= link_to 'Collection', collection_path, class: "nav-link" %>
                <%= link_to 'Chatrooms', chatrooms_path, class: "nav-link" %>
                <%= link_to 'Recommendations', recommendations_path, class: "nav-link" %>
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      
    </nav>


    <main>
      <%= yield %>
    </main>
  </body>
</html>